---
- name: Update apt cache
  apt: update_cache=yes
  tags: packages

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - pkg-config
    - erlang
    - libmozjs185-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - git
    - curl
    - nodejs
    - npm
    - python-sphinx
    - runit
    - python3-pip
  tags: packages

- name: Creating symbolic link node -> nodejs
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  tags: packages

- name: Download CouchDB from Github
  git: repo=https://github.com/apache/couchdb.git dest={{ couchdb_compile_dir }} accept_hostkey=yes version={{ couchdb_version }}
  tags: couchdb

- name: Remove erlang man folder
  file: path=/usr/lib/erlang/man state=absent
  tags: packages

- name: Run configure
  shell: ./configure --disable-docs chdir={{ couchdb_compile_dir }}
  tags: couchdb

- name: Run make release
  shell: make release chdir={{ couchdb_compile_dir }}
  tags: couchdb

- name: Copy CouchDB to install location
  command: cp -r {{ couchdb_compile_dir }}/rel/couchdb {{ couchdb_install_dir }}
  tags: couchdb

- name: Make directories
  file: path={{ item }} state=directory mode=0755 owner=ubuntu group=ubuntu
  with_items:
    - /var/log/couchdb
    - /etc/sv/couchdb/log
    - /mnt/couchdb/data
  tags: configure

- name: Create config files
  template: src={{ item }}.j2 dest={{ couchdb_install_dir }}/etc/{{ item }}
  with_items:
    - local.ini
    - vm.args
  tags: configure

- name: Change owner of CouchDB installation
  file: dest={{ couchdb_install_dir }} owner=ubuntu group=ubuntu mode=0755 recurse=yes
  tags: configure

- name: Create /etc/sv/couchdb/log/run script
  template:
    src: log.run.j2
    dest: /etc/sv/couchdb/log/run
    mode: 0744
    owner: ubuntu
    group: ubuntu
  tags: configure

- name: Create /etc/sv/couchdb/run script
  template:
    src: run.j2
    dest: /etc/sv/couchdb/run
    mode: 0744
    owner: ubuntu
    group: ubuntu
  tags: configure

- name: Creating symbolic link for service
  file:
    src: /etc/sv/couchdb/
    dest: /etc/service/couchdb
    state: link
  tags: configure

- name: Wait 10 seconds for services to start
  pause:
    seconds: 10
  tags: configure
