#  COMP90024 Project - Team 33
#  David Barrell (520704), Bobby Koteski (696567), Steve Dang (807773)

---
- name: Install CouchDB on all servers
  hosts: servers
  remote_user: ubuntu
  become: yes

  roles:
    - couchdb
    - cluster
    - harvester